//
//  SignUpPresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SignUpPresenter {

    // MARK: - Private properties

    private weak var view: SignUpViewProtocol!
    
    // MARK: - Public properties

    var interactor: SignUpInteractorProtocol!
    var router: SignUpRouterProtocol!

    // MARK: - Init

    required init(view: SignUpViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - SignUpPresenterProtocol

extension SignUpPresenter: SignUpPresenterProtocol {
    
    func configureView() {
        
    }
    
}
