//
//  SignUpRouter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignUpRouter {

    // MARK: - Private properties

    private weak var viewController: SignUpViewController!
    
    required init(viewController: SignUpViewController) {
        self.viewController = viewController
    }

}

// MARK: - Extensions

// MARK: - SignUpRouterProtocol

extension SignUpRouter: SignUpRouterProtocol {
    
}
