//
//  SignUpInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SignUpInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: SignUpPresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: SignUpPresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - SignUpInteractorProtocol

extension SignUpInteractor: SignUpInteractorProtocol {
    
}
