//
//  SignUpAssembly.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignUpAssembly: SignUpAssemblyProtocol {

    // MARK: - Module setup

    func configure(with viewController: SignUpViewController) {
        let presenter = SignUpPresenter(view: viewController)
        let interactor = SignUpInteractor(presenter: presenter)
        let router = SignUpRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }

}

