//
//  SignUpProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SignUpAssemblyProtocol: class {
    func configure(with viewController: SignUpViewController)
}

protocol SignUpViewProtocol: class {
    
}

protocol SignUpPresenterProtocol: class {
    
    func configureView()
}

protocol SignUpInteractorProtocol: class {
    
}

protocol SignUpRouterProtocol: class {
    
}
