//
//  SignInViewController.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignInViewController: UIViewController, UITextFieldDelegate {

    // MARK: - Dependencies
    
    var presenter: SignInPresenterProtocol!
    let configurator: SignInAssemblyProtocol = SignInAssembly()
    let viewsFactory: LoginInAppViewsFactoryProtocol = LoginInAppViewsFactory()
    
    // MARK: - Properties
    
    // MARK: - LifeStyle ViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        createAndSetupViews()
        presenter.configureView()
        
        addKeyBoardNotification()
        addGestureRecongizerContentView()
    }
    
    // MARK: - Setup Views
    
    lazy var signInScrollView: UIScrollView = UIScrollView()
    lazy var contentInScrollView: UIView = UIView()
    
    var signInTitleImageView: UIImageView!
    
    var loginWithLabel: UILabel!
    var socialButtonsStackView: UIStackView!
    
    var orLabel: UILabel!
    
    var emailTextField: MaterialTextField!
    var passwordTextField: MaterialTextField!
    
    var loginButton: MaterialButton!
    
    var needAnAccountLabel: UILabel!
    var signUpButton: MaterialButton!
    
    func createAndSetupViews() {
        view.backgroundColor = UIColor.Pallete.white
        
        signInTitleImageView = viewsFactory.buildTitleImageViewWith(image: .authorization)
        
        loginWithLabel = viewsFactory.buildStandartLabel(text: "Login with:".localized(with: .loginInAppFlow))
        socialButtonsStackView = viewsFactory.buildSocialButtonsStackView()
        
        orLabel = viewsFactory.buildStandartLabel(text: "or".localized(with: .loginInAppFlow))
        
        emailTextField = viewsFactory.buildAppTextField(placeHolderText: "Email".localized(with: .loginInAppFlow),
                                                         delegate: self)
        passwordTextField = viewsFactory.buildAppTextField(placeHolderText: "Password".localized(with: .loginInAppFlow),
                                                            delegate: self)
        
        loginButton = viewsFactory.buildStandartButton(text: "Login".localized(with: .loginInAppFlow))
        
        needAnAccountLabel = viewsFactory.buildStandartLabel(text: "Need an account?".localized(with: .loginInAppFlow))
        signUpButton = viewsFactory.buildStandartButton(text: "Sign up".localized(with: .loginInAppFlow))
        
        setupConstraints()
    }
    
   
    
    // MARK: - Keyboard with scrollView setup

    private var activeField: UITextField?
    private var lastOffset: CGPoint!
    
    private func addKeyBoardNotification() {
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(keyboard),
                                               name: UIResponder.keyboardWillHideNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(keyboard),
                                               name: UIResponder.keyboardWillChangeFrameNotification,
                                               object: nil)
    }
    
    private func addGestureRecongizerContentView() {
        self.contentInScrollView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(returnTextView(gesture:))))
    }
    
    @objc func returnTextView(gesture: UIGestureRecognizer) {
        guard activeField != nil else { return }
        activeField?.resignFirstResponder()
        activeField = nil
    }

    @objc func keyboard(notification: Notification) {
        guard let userInfo = notification.userInfo else { return }
        let keyboardScreenEndFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
        let keyboardViewEndFrame = view.convert(keyboardScreenEndFrame, to: view.window)
        
        if (notification.name == UIResponder.keyboardWillHideNotification) {
            signInScrollView.contentInset = UIEdgeInsets.zero
        } else {
            signInScrollView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: keyboardViewEndFrame.height, right: 0)
        }
        
        signInScrollView.scrollIndicatorInsets = signInScrollView.contentInset
    }
    
    func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        activeField = textField
        lastOffset = self.signInScrollView.contentOffset
        return true
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        activeField?.resignFirstResponder()
        activeField = nil
        return true
    }


}

// MARK: - Extensions

// MARK: - SignInViewProtocol

extension SignInViewController: SignInViewProtocol {
    
}

// MARK: - SwiftUI

import SwiftUI

struct SignInViewControllerProvider: PreviewProvider {
    static var previews: some View {
        ContainerView().edgesIgnoringSafeArea(.all)
    }
    struct ContainerView: UIViewControllerRepresentable {
        typealias UIViewControllerType = SignInViewController
        
        let viewController = SignInViewController()
        
        func makeUIViewController(context: Context) -> SignInViewController {
            return viewController
        }
        
        func updateUIViewController(_ uiViewController: SignInViewController, context: Context) {
            
        }
    }
}
