//
//  ProfileProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 23.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileAssemblyProtocol: class {
    func configure(with viewController: ProfileViewController)
}

protocol ProfileViewProtocol: class {
    
}

protocol ProfilePresenterProtocol: class {
    
    func configureView()
}

protocol ProfileInteractorProtocol: class {
    
}

protocol ProfileRouterProtocol: class {
    
}
