//
//  ProfilePresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 23.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProfilePresenter {

    // MARK: - Private properties

    private weak var view: ProfileViewProtocol!
    
    // MARK: - Public properties

    var interactor: ProfileInteractorProtocol!
    var router: ProfileRouterProtocol!

    // MARK: - Init

    required init(view: ProfileViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - ProfilePresenterProtocol

extension ProfilePresenter: ProfilePresenterProtocol {
    
    func configureView() {
        
    }
    
}
