//
//  ProfileRouter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 23.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileRouter {

    // MARK: - Private properties

    private weak var viewController: ProfileViewController!
    
    required init(viewController: ProfileViewController) {
        self.viewController = viewController
    }

}

// MARK: - Extensions

// MARK: - ProfileRouterProtocol

extension ProfileRouter: ProfileRouterProtocol {
    
}
