//
//  ProfileInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 23.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProfileInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: ProfilePresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: ProfilePresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - ProfileInteractorProtocol

extension ProfileInteractor: ProfileInteractorProtocol {
    
}
