//
//  AuthPresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 14.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AuthPresenter {

    // MARK: - Private properties

    private weak var view: AuthViewProtocol!
    
    // MARK: - Public properties

    var interactor: AuthInteractorProtocol!
    var router: AuthRouterProtocol!

    // MARK: - Init

    required init(view: AuthViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - AuthPresenterProtocol

extension AuthPresenter: AuthPresenterProtocol {
    
    func configureView() {
        
    }
    
    func tapLogin() {
        router.goToSignIn()
    }
    
}
