//
//  AuthRouter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 14.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AuthRouter {

    // MARK: - Private properties

    private weak var viewController: AuthViewController!
    
    required init(viewController: AuthViewController) {
        self.viewController = viewController
    }

}

// MARK: - Extensions

// MARK: - AuthRouterProtocol

extension AuthRouter: AuthRouterProtocol {
    
    func goToSignIn() {
        let vc = SignInViewController()
        viewController.present(vc, animated: true, completion: nil)
    }
}
