//
//  AuthProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 14.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AuthAssemblyProtocol: class {
    func configure(with viewController: AuthViewController)
}

protocol AuthViewProtocol: class {
    
}

protocol AuthPresenterProtocol: class {
    
    func configureView()
    func tapLogin()
}

protocol AuthInteractorProtocol: class {
    
}

protocol AuthRouterProtocol: class {
    func goToSignIn()
}
