//
//  MyChatsListInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MyChatsListInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: MyChatsListPresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: MyChatsListPresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - MyChatsListInteractorProtocol

extension MyChatsListInteractor: MyChatsListInteractorProtocol {
    
}
