//
//  MyChatsListAssembly.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MyChatsListAssembly: MyChatsListAssemblyProtocol {

    // MARK: - Module setup

    func configure(with viewController: MyChatsListViewController) {
        let presenter = MyChatsListPresenter(view: viewController)
        let interactor = MyChatsListInteractor(presenter: presenter)
        let router = MyChatsListRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }

}

