//
//  MyChatsListProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MyChatsListAssemblyProtocol: class {
    func configure(with viewController: MyChatsListViewController)
}

protocol MyChatsListViewProtocol: class {
    
}

protocol MyChatsListPresenterProtocol: class {
    
    func configureView()
}

protocol MyChatsListInteractorProtocol: class {
    
}

protocol MyChatsListRouterProtocol: class {
    
}
