//
//  MyChatsListPresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MyChatsListPresenter {

    // MARK: - Private properties

    private weak var view: MyChatsListViewProtocol!
    
    // MARK: - Public properties

    var interactor: MyChatsListInteractorProtocol!
    var router: MyChatsListRouterProtocol!

    // MARK: - Init

    required init(view: MyChatsListViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - MyChatsListPresenterProtocol

extension MyChatsListPresenter: MyChatsListPresenterProtocol {
    
    func configureView() {
        
    }
    
}
