//
//  ProfileViewController.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 23.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileViewController: UIViewController {

    // MARK: - Dependencies
    
    var presenter: ProfilePresenterProtocol!
    let configurator: ProfileAssemblyProtocol = ProfileAssembly()
    let viewsFactory: LoginInAppViewsFactoryProtocol = LoginInAppViewsFactory()
    
    // MARK: - Properties
    
    // MARK: - LifeStyle ViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        createAndSetupViews()
        presenter.configureView()
        
        addKeyBoardNotification()
        addGestureRecongizerContentView()
        
    }
    
    // MARK: - Setup Views
    
    lazy var profileScrollView: UIScrollView = UIScrollView()
    lazy var contentInScrollView: UIView = UIView()
    
    var setupProfileTitleImageView: UIImageView!
    
    var addPhotoView: AddPhotoView!
    
    var fullNameTextField: UITextField!
    var aboutMeTextField: UITextField!
    
    var sexLabel: UILabel!
    var sexSegmentControl: MaterialSegmentedControl!
    
    var goToChatsButton: MaterialButton!
    
    func createAndSetupViews() {
        view.backgroundColor = UIColor.Pallete.white
        
        setupProfileTitleImageView = viewsFactory.buildTitleImageViewWith(image: .setUpProfile)
        
        addPhotoView = viewsFactory.buildAddPhotoView()
        
        fullNameTextField = viewsFactory.buildAppTextField(placeHolderText: "Full name".localized(with: .loginInAppFlow),
                                                                  delegate: self)
        aboutMeTextField = viewsFactory.buildAppTextField(placeHolderText: "About me".localized(with: .loginInAppFlow),
        delegate: self)
        
        sexLabel = viewsFactory.buildStandartLabel(text: "Sex".localized(with: .loginInAppFlow))
        
        let male = "Male".localized(with: .loginInAppFlow)
        let female = "Female".localized(with: .loginInAppFlow)
        print(male)
        sexSegmentControl = viewsFactory.buildSegmentControlWith(segmentsText: [male,
                                                                                female ])
        
        goToChatsButton = viewsFactory.buildStandartButton(text: "Go to chats!".localized(with: .loginInAppFlow))
        
        
        setupConstraints()
    }
    
   
    // MARK: - Keyboard with scrollView setup

    private var activeField: UITextField?
    private var lastOffset: CGPoint!
    
    private func addKeyBoardNotification() {
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(keyboard),
                                               name: UIResponder.keyboardWillHideNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(keyboard),
                                               name: UIResponder.keyboardWillChangeFrameNotification,
                                               object: nil)
    }
    
    private func addGestureRecongizerContentView() {
        self.contentInScrollView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(returnTextView(gesture:))))
    }
    
    @objc func returnTextView(gesture: UIGestureRecognizer) {
        guard activeField != nil else { return }
        activeField?.resignFirstResponder()
        activeField = nil
    }

    @objc func keyboard(notification: Notification) {
        guard let userInfo = notification.userInfo else { return }
        let keyboardScreenEndFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
        let keyboardViewEndFrame = view.convert(keyboardScreenEndFrame, to: view.window)
        
        if (notification.name == UIResponder.keyboardWillHideNotification) {
            profileScrollView.contentInset = UIEdgeInsets.zero
        } else {
            profileScrollView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: keyboardViewEndFrame.height, right: 0)
        }
        
        profileScrollView.scrollIndicatorInsets = profileScrollView.contentInset
    }
    
    func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        activeField = textField
        lastOffset = self.profileScrollView.contentOffset
        return true
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        activeField?.resignFirstResponder()
        activeField = nil
        return true
    }

}

// MARK: - Extensions

// MARK: - ProfileViewProtocol

extension ProfileViewController: ProfileViewProtocol {
    
}

// MARK: - TextViewDelegate

extension ProfileViewController: UITextFieldDelegate {
    
}

// MARK: - SwiftUI

import SwiftUI

struct ProfileViewControllerProvider: PreviewProvider {
    static var previews: some View {
        ContainerView().edgesIgnoringSafeArea(.all)
    }
    struct ContainerView: UIViewControllerRepresentable {
        typealias UIViewControllerType = ProfileViewController
        
        let viewController = ProfileViewController()
        
        func makeUIViewController(context: Context) -> ProfileViewController {
            return viewController
        }
        
        func updateUIViewController(_ uiViewController: ProfileViewController, context: Context) {
            
        }
    }
}
