//
//  AuthInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 14.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AuthInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: AuthPresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: AuthPresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - AuthInteractorProtocol

extension AuthInteractor: AuthInteractorProtocol {
    
}
