//
//  AuthAssembly.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 14.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AuthAssembly: AuthAssemblyProtocol {

    // MARK: - Module setup

    func configure(with viewController: AuthViewController) {
        let presenter = AuthPresenter(view: viewController)
        let interactor = AuthInteractor(presenter: presenter)
        let router = AuthRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }

}

