//
//  PeopleListAssembly.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PeopleListAssembly: PeopleListAssemblyProtocol {

    // MARK: - Module setup

    func configure(with viewController: PeopleListViewController) {
        let presenter = PeopleListPresenter(view: viewController)
        let interactor = PeopleListInteractor(presenter: presenter)
        let router = PeopleListRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }

}

