//
//  PeopleListInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PeopleListInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: PeopleListPresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: PeopleListPresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - PeopleListInteractorProtocol

extension PeopleListInteractor: PeopleListInteractorProtocol {
    
}
