//
//  PeopleListViewController.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PeopleListViewController: UIViewController {

    // MARK: - Custom types
    
    // MARK: - Outlets
    
    // MARK: - Public Properties
    
    var presenter: PeopleListPresenterProtocol!
    let configurator: PeopleListAssemblyProtocol = PeopleListAssembly()
    
    // MARK: - Private Properties
    
    
    // MARK: - LifeStyle ViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        createAndSetupViews()
        presenter.configureView()
        
    }
    
    // MARK: - Setup Views
    
    private func createAndSetupViews() {
        
        view.backgroundColor = UIColor.Pallete.white
        
        setupSearchBar()
        
    }
    
    
    // MARK: Set up SearchBar

    private func setupSearchBar() {
        navigationController?.navigationBar.barTintColor = UIColor.Pallete.white
        navigationController?.navigationBar.shadowImage = UIImage()
        
        let searchController = UISearchController(searchResultsController: nil)
        searchController.searchBar.tintColor = UIColor.Pallete.lightGreen
        searchController.searchBar.searchTextField.backgroundColor = UIColor.Pallete.gray
        navigationItem.searchController = searchController
        
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.hidesNavigationBarDuringPresentation = false
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.delegate = self
    }
    
    // MARK: Set up CollectionView
    
    // MARK: - Public methods
    
    // MARK: - Private methods

}

// MARK: - Extensions

// MARK: - PeopleListViewProtocol

extension PeopleListViewController: PeopleListViewProtocol {
    
}

// MARK: - UISearchBarDelegate

extension PeopleListViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        print(searchText)
    }
}

// MARK: - SwiftUI

import SwiftUI

struct PeopleListViewViewControllerProvider: PreviewProvider {
    static var previews: some View {
        ContainerView().edgesIgnoringSafeArea(.all)
    }
    struct ContainerView: UIViewControllerRepresentable {
        typealias UIViewControllerType = MainTabBarController
        
        let viewController = MainTabBarController()
        
        func makeUIViewController(context: Context) -> MainTabBarController {
            return viewController
        }
        
        func updateUIViewController(_ uiViewController: MainTabBarController, context: Context) {
            
        }
    }
}
