//
//  PeopleListPresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PeopleListPresenter {

    // MARK: - Private properties

    private weak var view: PeopleListViewProtocol!
    
    // MARK: - Public properties

    var interactor: PeopleListInteractorProtocol!
    var router: PeopleListRouterProtocol!

    // MARK: - Init

    required init(view: PeopleListViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - PeopleListPresenterProtocol

extension PeopleListPresenter: PeopleListPresenterProtocol {
    
    func configureView() {
        
    }
    
}
