//
//  PeopleListProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 19.10.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PeopleListAssemblyProtocol: class {
    func configure(with viewController: PeopleListViewController)
}

protocol PeopleListViewProtocol: class {
    
}

protocol PeopleListPresenterProtocol: class {
    
    func configureView()
}

protocol PeopleListInteractorProtocol: class {
    
}

protocol PeopleListRouterProtocol: class {
    
}
