//
//  SignInPresenter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SignInPresenter {

    // MARK: - Private properties

    private weak var view: SignInViewProtocol!
    
    // MARK: - Public properties

    var interactor: SignInInteractorProtocol!
    var router: SignInRouterProtocol!

    // MARK: - Init

    required init(view: SignInViewProtocol) {
        self.view = view
    }
    
}

// MARK: - Extensions

// MARK: - SignInPresenterProtocol

extension SignInPresenter: SignInPresenterProtocol {
    
    func configureView() {
        
    }
    
}
