//
//  SignInRouter.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignInRouter {

    // MARK: - Private properties

    private weak var viewController: SignInViewController!
    
    required init(viewController: SignInViewController) {
        self.viewController = viewController
    }

}

// MARK: - Extensions

// MARK: - SignInRouterProtocol

extension SignInRouter: SignInRouterProtocol {
    
}
