//
//  SignInViewController.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignInViewController: UIViewController {

    // MARK: - Dependencies
    
    var presenter: SignInPresenterProtocol!
    let configurator: SignInAssemblyProtocol = SignInAssembly()
    let viewsFactory: AuthViewsFactoryProtocol = AuthViewsFactory()
    
    // MARK: - Properties
    
    // MARK: - LifeStyle ViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
        
        
    }
    
    // MARK: - Setup Views
    
    // MARK: Setup Constraints
    
    // MARK: - Public methods
    
    // MARK: - Private methods

}

// MARK: - Extensions

// MARK: - SignInViewProtocol

extension SignInViewController: SignInViewProtocol {
    
}
