//
//  SignInInteractor.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SignInInteractor {
    
    // MARK: - Private properties
    
    private weak var presenter: SignInPresenterProtocol!
    
    // MARK: - Init
    
    required init(presenter: SignInPresenterProtocol) {
        self.presenter = presenter
    }
    
}

// MARK: - Extensions

// MARK: - SignInInteractorProtocol

extension SignInInteractor: SignInInteractorProtocol {
    
}
