//
//  SignInProtocols.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SignInAssemblyProtocol: class {
    func configure(with viewController: SignInViewController)
}

protocol SignInViewProtocol: class {
    
}

protocol SignInPresenterProtocol: class {
    
    func configureView()
}

protocol SignInInteractorProtocol: class {
    
}

protocol SignInRouterProtocol: class {
    
}
