//
//  SignInAssembly.swift
//  SimpleMeet
//
//  Created by Дмитрий Федоринов on 21.07.2020.
//  Copyright (c) 2020 Дмитрий Федоринов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignInAssembly: SignInAssemblyProtocol {

    // MARK: - Module setup

    func configure(with viewController: SignInViewController) {
        let presenter = SignInPresenter(view: viewController)
        let interactor = SignInInteractor(presenter: presenter)
        let router = SignInRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }

}

